### ISSUE TITLE
Could you give an example where data is being loaded locally?

### ISSUE THREAD

**Issue by JoeHasell** [quarto-ext/shinylive#7]
Hi there!

Thanks very much for your amazing work.

I came to shinylive because I was looking for a way to get my shiny apps onto my netlify webpage without having to host them at e.g. shinyapp.io (where I'd have to pay above a certain useage).

I'm fairly comfortable making shiny apps and with R and RMarkdown. But I'm pretty new to Python, and my technical knowledge of what's going on behind the scenes here is very limited.

My apologies for asking what seems like a very basic question. I managed to get your example up and running in a Quarto web project published to netlify, but I'm struggling to figure out how to make an app that is reading data locally. I don't really get what is going on with the file structures and how to refer to them.

For instance, what I'd like to do is something like this:

```
def server(input, output, session):
    @output
    @render.table
    def table():
    
        df = pd.read_csv(WHAT_GOES_HERE?)
      
        return df
```
I tried various guesses at 'WHAT_GOES_HERE', and various file structures but couldn't ever find a way to read in the data.

I'd really appreciate it if you could explain, or perhaps put up an example that would help me see how to do this.

Many thanks in advance!

**Comment by AlFontal** [comment]
Hey, I am actually having trouble with this as I am unable to work with multiple files within a quarto document and I have no clue whether it is even possible to make this work in that kind of setting.

For what you want, however, the nomenclature should be something akin to:

```python
from pathlib import Path

def server(input, output, session):
    @output
    @render.table
    def table():
        infile = Path(__file__).parent / "your_file.csv"
        df = pd.read_csv(infile)
        return df

```

What I am struggling to get, however, is that `file.csv` bundled in a standalone shinylive-python cell... I will open an issue for that, however.

**Comment by JoeHasell** [comment]
Hey @AlFontal – thanks for your comment!

I also tried reading in the data in a python or r cell and then passing the object to the sinylive-python cell, but didn't have any luck with that either.

Glad to hear this isn't me just being dumb! Thanks again for your help.

**Comment by JoeHasell** [comment]
Oh wow! Thanks for thinking outside the box. I guess for smaller datasets, it's also best to just pull it in with an HTTP request. It was because the data is pretty large that I was thinking of reading it locally (and hence is also not very compatible with the work around you are suggesting).
Thanks again for you help though!

**Comment by AlFontal** [comment]
Indeed, it's just an ugly patch so far hahaha

In any case, I did try the HTTP request solution beforehand, but couldn't make it work since `shinylive` runs on `pyodide` under the hood, and since pyodide runs completely on the client's browser, it is very limited on the external requests it can make (and it doesn't handle sockets so far). I am way out of depth here on my very limited networking knowledge but you can read [pyodide's docs on the issue](https://pyodide.org/en/stable/usage/faq.html#how-can-i-load-external-files-in-pyodide).

You can't run a simple `pd.read_csv(url)` since it probably uses either `requests` or `urllib` under the hood which are not supported... but I suspect some solution using `pyodide`'s API might exist.

**Comment by AlFontal** [comment]
Indeed, turns out it was way easier than that, you can do HTTP requests but using `pyodide.http.open_url`, so just do:

```python
from pyodide.http import open_url

df = pd.read_csv(open_url('url_to_your_table.csv'))
```
That seems to be working with no issues on my end.

**Comment by wch** [comment]
I believe the Quarto team is planning on making it easier to embed multiple files in a code chunk, but I don't know the exact plans and roadmap.

**Comment by gcgbarbosa** [comment]
Is this still an issue? Have we found a solution for this?

**Comment by georgestagg** [comment]
There are now a couple of ways to handle external data for a Shinylive app in Quarto. Either of the two following methods can be used:

1) Include the data as part of additional resources in your Quarto document's YAML header, then load the data from the static web server using Pyodide's `open_url()`. For example, if there is the file `mtcars.csv` in the directory `data/`:

````md
---
title: Shinylive in Quarto
format: html
filters:
  - shinylive
resources:
  - data/mtcars.csv
---

:::{.column-screen}

```{shinylive-python}
#| standalone: true
#| viewerHeight: 600
from shiny import *
from pyodide.http import open_url
import pandas as pd

app_ui = ui.page_fluid(
    ui.output_table(id="table"),
)

def server(input, output, session):
    @output
    @render.table
    def table():
        df = pd.read_csv(open_url('/data/mtcars.csv'))
        return df

app = App(app_ui, server)
```

:::
````

2) Or, use Garrick's `quarto-base64` extension to include the additional content directly in your Shinylive blocks, embedded as a base64 encoded binary file: [Further documentation](https://pkg.garrickadenbuie.com/quarto-base64/).

**Comment by jack-davison** [comment]
Hi @gadenbuie, sorry to reopen this issue with a different (although related) topic:

```python
df = pd.read_csv(open_url('/data/mtcars.csv'))
```

Is there an R equivalent to this? I've tried just subbing in `read.csv()` in R, but my developer tools on render suggest it can't find the file/directory.

Or is reading "local" files not possible in the R version of shinylive on quarto?

**Comment by georgestagg** [comment]
Something like the following should work for R:

````markdown
---
title: Shinylive in Quarto
format: html
filters:
  - shinylive
---

:::{.column-screen}

```{shinylive-r}
#| standalone: true
#| viewerHeight: 600

ui = tableOutput('table')
server = function(input, output) {
df <- read.csv("example_table.csv")
    output$table <- renderTable(df)
}
shinyApp(ui, server)

## file: example_table.csv
name,x,y
foo,1,1
bar,2,3
waldo,2
fred,4
plugh,5
thud,7
```

:::
````

You can also use the `quarto-base64` extension to include local files here, rather than directly embedding content, e.g.

```markdown
## file: example_table.csv
## type: binary
{{< base64 example_table.csv >}}
```

Finally, you can use the base R function `url()` or `download.file()` to access content. However, in this case you'll need to know the URL for where the file is available at the time of authoring:

````markdown
```{shinylive-r}
#| standalone: true
#| viewerHeight: 600

ui = tableOutput('table')
server = function(input, output) {
df <- read.csv(url("https://gist.githubusercontent.com/RobVanGroenewoud/ba89ad7684df8cefe5c183adb498cc65/raw/f2eec6d2cb89f5d779e16b28ed0dab89d738ba96/sample.csv"))
    output$table <- renderTable(df)
}
shinyApp(ui, server)

```
````

Since this thread now contains multiple examples showing how this can be done both for R and Python I'm going to mark it as completed. However do feel free to continue the conversation below if you have any other questions or issues.
